### ISSUE TITLE
Several errors with the item sprites

### ISSUE THREAD

**Issue by jpirnat** [msikma/pokesprite#100]
I was going through this repository's item sprites for an unrelated project, and I noticed several errors/missing sprites.

1. "item_0450" in item-map.json should be "key-item/bike-green", not "key-item/bike--yellow". As far as I can tell, item 450 has been the green bike sprite since gen 6. (This also means "item_0713": "key-item/bike--yellow" should be included, rather than skipped as a duplicate.)

2. The gen 3 sprites for Mach Bike, Acro Bike, Lift Key, and Gold Teeth are missing. This repository only contains the sprites for gen 6+ (for Mach Bike/Acro Bike) or gen 7+ (for Lift Key/Gold Teeth)
Reference images:
https://bulbapedia.bulbagarden.net/wiki/File:Bag_Mach_Bike_III_Sprite.png (for gen 3)
https://bulbapedia.bulbagarden.net/wiki/File:Bag_Mach_Bike_Sprite.png (for gen 6+)
https://bulbapedia.bulbagarden.net/wiki/File:Bag_Acro_Bike_III_Sprite.png (for gen 3)
https://bulbapedia.bulbagarden.net/wiki/File:Bag_Acro_Bike_Sprite.png(for gen 6+)
https://bulbapedia.bulbagarden.net/wiki/File:Bag_Lift_Key_III_Sprite.png (for gen 3)
https://bulbapedia.bulbagarden.net/wiki/File:Bag_Lift_Key_Sprite.png (for gen 7+)
https://bulbapedia.bulbagarden.net/wiki/File:Bag_Gold_Teeth_III_Sprite.png (for gen 3)
https://bulbapedia.bulbagarden.net/wiki/File:Bag_Gold_Teeth_Sprite.png (for gen 7+)

3. The "legacy" sprites for Razz Berry and Nanab Berry are still the current sprites. The sprites that this repository lists as the "current" sprites for those items are only used in gen 7's Let's Go Pikachu/Eevee games.

4. The real gen 5 sprite for Dowsing Machine is missing. The legacy sprite that this repository lists as Dowsing Machine's gen 5 sprite is actually the sprite for gen 4.
https://bulbapedia.bulbagarden.net/wiki/File:Bag_Dowsing_MCHN_IV_Sprite.png (for gen 4)
https://bulbapedia.bulbagarden.net/wiki/File:Bag_Dowsing_MCHN_Sprite.png (for gen 5)

I know this repository focuses primarily on the Pokémon sprites and not the item sprites, but I thought it wouldn't hurt to let you know about these issues.

**Comment by msikma** [comment]
Thanks for letting me know! Sorry for such a late response. I'll go and have a look. Like you mention, the main focus of the repo is the Pokémon sprites, but since the items are there I don't want to do a poor job with them.

**Comment by msikma** [comment]
A little late again, but just made a PR for fixing this.
