### ISSUE TITLE
Gen 8 Mr. Mime (Kanto) sprite is incorrect

### ISSUE THREAD

**Issue by ercdndrs** [msikma/pokesprite#103]
I noticed that the sprite for Mr. Mime seems to be incorrect for Gen 8. I found one that seems to match better on PokemonDB, but the scaling and padding is inconsistent with your format so I don't feel comfortable adding it to the repo myself. I have attached the new sprite and a screenshot of Mr. Mime's sprite being shown in game as proof of the match (and mismatch to the existing sprite in the repo). Thanks for your work!
![mr-mime](https://user-images.githubusercontent.com/55447330/112234597-3ec07680-8c13-11eb-8012-af4ae962a98f.png)
![Mr-Mime-DA](https://user-images.githubusercontent.com/55447330/112234707-78917d00-8c13-11eb-9f34-9764cef702fa.png)

**Comment by msikma** [comment]
Thanks, good catch. It's weird, because the version I have is actually lifted directly from the DLC. But I guess they changed it in a minor update.

**Comment by msikma** [comment]
New version:

![mr-mime](https://user-images.githubusercontent.com/1507745/116438125-6fb54c00-a84e-11eb-911d-bf9523472071.png)

![mr-mime](https://user-images.githubusercontent.com/1507745/116438154-75ab2d00-a84e-11eb-932a-994a3af4ea5d.png)

**Comment by ercdndrs** [comment]
Perfect; thank you!
