### ISSUE TITLE
Gen 8 changed shiny Combusken's colors

### ISSUE THREAD

**Issue by Lusamine** [msikma/pokesprite#104]
The gen 8 Combusken model was changed to be much more noticeably red than in previous generations.

https://github.com/msikma/pokesprite/blob/master/pokemon-gen8/shiny/combusken.png

Reference: https://www.serebii.net/pokedex-swsh/combusken/

Blaziken may have also been slightly tweaked, but the difference is much more subtle if so.

**Comment by msikma** [comment]
Thanks for the report. I've made a new version. I think Blaziken is still OK, judging by the Serebii image.

Here's the new version, do you think this is better?

![combusken](https://user-images.githubusercontent.com/1507745/116438048-5b714f00-a84e-11eb-8ac8-50bf63d61c67.png)
 ![combusken](https://user-images.githubusercontent.com/1507745/116438033-56ac9b00-a84e-11eb-8133-45fcf1c270d4.png)

**Comment by msikma** [comment]
Merged the new version, so I'm closing this.
