### ISSUE TITLE
Unnoticed LGPE => SWSH Sprite Changes

### ISSUE THREAD

**Issue by sora10pls** [msikma/pokesprite#106]
Related: #103 

Turns out, after looking at the above issue, there are a handful of large sprites from LGPE that got very minor adjustments in SWSH that went unnoticed for a long time. The affected species are (from that I've noticed):

- Charizard
- Clefable
- Vileplume
- Machamp
- Rapidash
- Cloyster
- Gengar
- Onix
- Kingler
- Hitmonchan
- Seaking
- Mr. Mime (included because your prior commit uses a sprite that's slightly misaligned with the sprite from my ROM dump)
- Gyarados
- Lapras
- Snorlax
- Mewtwo
- Melmetal

[Attached here](https://github.com/msikma/pokesprite/files/6475187/icon_pokemon_kanto.zip) are all of the Kanto Pokémon sprites (+ Meltan/Melmetal) dumped from the SWSH ROM. The above list is just the ones I noticed, but maybe you'll find other, smaller oddities.

Some were simply shifted a few pixels over (Charizard, Lapras) while some others received some minor updates (Rapidash's flames are now outlined black, Kingler is a brighter orange, among other changes).

Rapidash from this repository:
![image](https://user-images.githubusercontent.com/17801814/118190418-184bda00-b411-11eb-9786-127e2893c51b.png)
Rapidash from SWSH ROM:
![poke_icon_0078_00s_n](https://user-images.githubusercontent.com/17801814/118190388-0b2eeb00-b411-11eb-9f8d-c7892d56a67a.png)

**Comment by msikma** [comment]
Thank you for reporting these, and sorry for being late. I'm going to get started on them when I've got some time soon.

**Comment by msikma** [comment]
I think they're all correct now. If I didn't miss anything I'll push the update.
 ![charizard](https://user-images.githubusercontent.com/1507745/139605188-1daf48d0-c14d-4f32-89f5-e97309249d97.png) ![clefable](https://user-images.githubusercontent.com/1507745/139605189-b498c436-812c-40aa-9cbe-d47d22d8e516.png) ![cloyster](https://user-images.githubusercontent.com/1507745/139605190-a2dc74ef-081e-4d7d-b347-48fb8bdfb00f.png) ![gengar](https://user-images.githubusercontent.com/1507745/139605192-212977fc-e9a8-4b6e-98bf-5825a6b81d82.png) ![gyarados](https://user-images.githubusercontent.com/1507745/139605194-24c4b6ec-a893-46df-be2a-55c6e3d96725.png) ![hitmonchan](https://user-images.githubusercontent.com/1507745/139605195-4bdaffe8-77e5-4ba9-be90-210d3c5e0b43.png) ![kingler](https://user-images.githubusercontent.com/1507745/139605197-6fdf45ce-4c14-464c-b2d2-c3a6a959ea26.png) ![lapras](https://user-images.githubusercontent.com/1507745/139605198-eabff4a9-0e82-4a56-93a8-2f06a3cf90c3.png) ![machamp](https://user-images.githubusercontent.com/1507745/139605199-6139cf50-d979-4066-a3b0-18b9d9f24946.png) ![melmetal](https://user-images.githubusercontent.com/1507745/139605200-93672e4c-00b6-494c-a1e3-9fad13e064f9.png) ![mewtwo](https://user-images.githubusercontent.com/1507745/139605201-9441738e-42c1-45cc-8ca6-c4c79cfc9d82.png) ![mr-mime](https://user-images.githubusercontent.com/1507745/139605202-dab523a2-40b1-42c2-81db-0dfdb6d399c3.png) ![onix](https://user-images.githubusercontent.com/1507745/139605203-16f77ff5-b574-4c24-a07e-55ef38a55af3.png) ![rapidash](https://user-images.githubusercontent.com/1507745/139605204-dbadde83-2562-411a-8a6b-861ac4372f09.png) ![seaking](https://user-images.githubusercontent.com/1507745/139605205-f04609cc-968c-4d9e-8efa-b3b5de68714c.png) ![snorlax](https://user-images.githubusercontent.com/1507745/139605206-2a4edc5a-fb5d-4182-a18e-8bdb54642cd6.png) ![vileplume](https://user-images.githubusercontent.com/1507745/139605207-778c9ae6-7ba8-4d28-ae78-8f550f788b98.png)

 ![charizard_shiny](https://user-images.githubusercontent.com/1507745/139605217-f10934c7-a0a3-412a-8fdc-0ba2c756305a.png) ![clefable_shiny](https://user-images.githubusercontent.com/1507745/139605218-555c377f-eebe-4e04-be05-c7ed3009af3f.png) ![cloyster_shiny](https://user-images.githubusercontent.com/1507745/139605219-762ae120-6e59-4991-884e-248ad371956a.png) ![gengar_shiny](https://user-images.githubusercontent.com/1507745/139605220-8aa9063b-cce8-4f55-abfc-0ddd78235755.png) ![gyarados_shiny](https://user-images.githubusercontent.com/1507745/139605222-3e2395e4-d848-4207-9704-8f38a05a549b.png) ![hitmonchan_shiny](https://user-images.githubusercontent.com/1507745/139605224-7ffc5b15-0af8-4087-9292-b79cbf61fd26.png) ![kingler_shiny](https://user-images.githubusercontent.com/1507745/139605225-8c9b2f16-c28e-482f-919b-37baed537b05.png) ![lapras_shiny](https://user-images.githubusercontent.com/1507745/139605227-3e88cf5e-1831-4972-82e9-ac0b11fa59f0.png) ![machamp_shiny](https://user-images.githubusercontent.com/1507745/139605228-7ab7c950-8cd5-4947-b7c2-6e4172df5b08.png) ![melmetal_shiny](https://user-images.githubusercontent.com/1507745/139605229-5b1fe9f6-82a5-4344-8bcb-5df03758aaf6.png) ![mewtwo_shiny](https://user-images.githubusercontent.com/1507745/139605230-a4cfc573-4c73-4cb5-b9ef-b5b5fd840e86.png) ![mr-mime_shiny](https://user-images.githubusercontent.com/1507745/139605231-401f34ec-1ede-4ae0-b52d-1beb4060b8bd.png) ![onix_shiny](https://user-images.githubusercontent.com/1507745/139605232-cb9dc35a-1174-4ea5-95db-d468b43210d9.png) ![rapidash_shiny](https://user-images.githubusercontent.com/1507745/139605233-4c772aec-1cce-4666-88b0-0b95821465a3.png) ![seaking_shiny](https://user-images.githubusercontent.com/1507745/139605234-cbe66dc6-fa68-413f-939d-6242db3f6479.png) ![snorlax_shiny](https://user-images.githubusercontent.com/1507745/139605235-f07d9c1c-4673-4799-bb26-6a45ea7997c6.png) ![vileplume_shiny](https://user-images.githubusercontent.com/1507745/139605236-bdd8607f-0781-4dc2-b460-01f64d4059c0.png)

**Comment by sora10pls** [comment]
All looks great, no inconsistencies when comparing vanilla sprites and Shiny sprites with PKHeX. Thanks a bunch!

**Comment by msikma** [comment]
Merged and published to npm
