### ISSUE TITLE
Arceus sprites

### ISSUE THREAD

**Issue by Kirzi** [msikma/pokesprite#11]
Posting here as requested.

http://i.imgur.com/yj55AOP.png

Just some normal/shiny Arceus sprites I made with the various plates.

**Comment by msikma** [comment]
Fixed as of [the latest commit](https://github.com/msikma/pokesprite/commit/b0277007c2ffb837b66ac4db89b1b820d94f6b5a). I ended up custom making some new sprites anyway, since I had some things I wanted slightly different.
