### ISSUE TITLE
Custom female Wobbuffet sprites.

### ISSUE THREAD

**Issue by jeroenpastoor** [msikma/pokesprite#114]
Wobbuffet stood out to me as a Pokémon that, like for example Pikachu, has a very clear gender difference.

I've made my own female variations of the regular and shiny sprites for both gen-7 and gen-8, which I would love to contribute to this project:
![wobbuffet](https://user-images.githubusercontent.com/8515690/149536759-eb6973f1-be7e-47b7-94cc-2f3f269f3773.png) ![wobbuffet](https://user-images.githubusercontent.com/8515690/149536777-dcb7d53d-ec31-4e3f-a699-3277e9559804.png)
![wobbuffet](https://user-images.githubusercontent.com/8515690/149536716-875c1654-6425-46f2-a8d7-990bb4fdae6e.png) ![wobbuffet](https://user-images.githubusercontent.com/8515690/149536734-6f984a23-a26e-45ef-a509-a8f748861a56.png)

**Comment by msikma** [comment]
They look great. I've just merged them. Thanks for your contribution!
