### ISSUE TITLE
Missing Galarian Sprites

### ISSUE THREAD

**Issue by Ensamma** [msikma/pokesprite#119]
Missing all Galarian shiny sprites outside of Slowpoke

**Comment by koenigderluegner** [comment]
You're probably looking in the wrong directory. Theres a total of 3 pokemon folder. the one in /icons/pokemon, which is outdated and has only the Slowpoke-Galar, Then there is [pokemon-gen7x](https://github.com/msikma/pokesprite/tree/master/pokemon-gen7x) which holds sprites before their Gen8 update came. Lastly there's [pokemon-gen8](https://github.com/msikma/pokesprite/tree/master/pokemon-gen8) which holds the most up-to-date icons including all galar forms

**Comment by Ensamma** [comment]
Thank you for taking the time to respond. Sorry I didn’t see those! Am updating a Google sheet and was following the naming convention then couldn’t find it by searching other folders. I’ll look through the ones you mentioned.

**Comment by msikma** [comment]
Yeah, all the ones in `/icons/pokemon` are old/legacy, they'll continue to be there for compatibility only.
