### ISSUE TITLE
Hippopotas and Hippowdon

### ISSUE THREAD

**Issue by JFSushi** [msikma/pokesprite#12]
Hey mate. 

First off, amazing work. Big fan of the shiny sprites.

I noticed there's something wrong with the Hippopotas and Hippowdon sprites. These guys have different forms (colours) based on gender, but here the male are listed as the regular sprite, while the regular female is listed as the shiny. Neither the male of female shinies are included.

A friend of mine recoloured the regular sprites to the shiny colours and said you could use them if you wanted.

[Shiny Male Hippopotas](https://cdn.discordapp.com/attachments/202519166866030602/228953208498814976/hippo.png)
[Shiny Female Hippopotas](https://cdn.discordapp.com/attachments/202519166866030602/228953307958345728/hippos.png)
[Shiny Male Hippowdon](https://cdn.discordapp.com/attachments/202519166866030602/228953203855720449/hipo.png)
[Shiny Female Hippowdon](https://cdn.discordapp.com/attachments/202519166866030602/228953207047454720/hipos.png)

**Comment by msikma** [comment]
You're absolutely right. I probably misread the Bulbapedia page when I was doing this. Never used a Hippopotas or Hippowdon so I didn't know about their gender differences.

I'll try to fix this. Could you give me your friend's name (or nickname)? I'd like to keep every contributor properly attributed.

**Comment by JFSushi** [comment]
Thank you! He goes by MattKuro.

**Comment by msikma** [comment]
I checked and the game actually does not display a special icon for female Hippopotas/Hippowdon, so I'll just move my own old "shiny" icon to the female directory. I don't like making unofficial sprites for the non-shiny section, but it's a bit weird they left this one out.

**Comment by msikma** [comment]
Final sprites I ended up using. Fixed now, next release they'll be there.

<img width="356" alt="screen shot 2016-12-11 at 01 44 59" src="https://cloud.githubusercontent.com/assets/1507745/21077192/76dd2f14-bf43-11e6-9038-a2801692ad46.png">
