### ISSUE TITLE
Shiny Tentacruel sprite colors

### ISSUE THREAD

**Issue by Moonboy65** [msikma/pokesprite#120]
heya, just wanted to let ya know that the Shiny Tentacruel sprite is the same color as Tentacool when it's shiny is like an indigo blue color instead of pink.

It should look like this:
![073](https://user-images.githubusercontent.com/14064784/164135397-0736d6d5-8f46-4c73-8fdc-bf10ce43768b.png)

Based on it's  current shiny color palette, i used the colors from it's Gen 5 sprite:
![073](https://user-images.githubusercontent.com/14064784/164135494-6bdd1c3f-5525-438e-878d-26fd04acaa87.png)

**Comment by msikma** [comment]
![tentacruel](https://user-images.githubusercontent.com/1507745/164216275-cdb60fa7-6483-415b-b1f5-fc7800f535dc.png)

You're right, it is a little too violet as it is now. I'll polish it up a bit.

**Comment by Moonboy65** [comment]
this seems to be for both the Gen 8 and Gen 7 sprites, thx for updating it!

**Comment by msikma** [comment]
I know this is a bit late but I've just made an updated sprite for this, and will be merging it soon!
