### ISSUE TITLE
Pixel Sprites for Hisui Balls dumped from HOME

### ISSUE THREAD

**Issue by The-Crimson-V** [msikma/pokesprite#121]
![FTAMoqPXoAMmlOH](https://user-images.githubusercontent.com/80659147/169327876-22c2dc66-e2f1-4372-9444-47d014f0247e.png)
Pokémon HOME introduced new sprites for the ancient Hisui balls for Pokémon Legends Arceus, and the dump was from @mattyoukhana_ on Twitter, although before they get added we'll have to wait until matt gives us a new image to work with since the image in question has what seems to be a little bit of jpg artifacting (non-white pixels can be seen in the white borders around the balls). I'm also hoping this isn't what the base image file looks like either. Apologies if any of this looks unprofessional, I don't use GitHub but wanted to contribute to this.

**Comment by koenigderluegner** [comment]
I already got a dump from @mattyoukhana_ (or [sora10pls](https://github.com/sora10pls) on GitHub) and plan to make a PR this weekend. 
I noticed that they're twice the size of our sprites, normally you can just decrease the size by 50% but those sprites are more detailed and will lose information when resizing. 
For my PR I'll ignore this fact and will offer a solution with resized icons. I'll leave the decision to @msikma as the owner to decide. if that's good enough.
