### ISSUE TITLE
[REQUEST] Origin Marks under Misc

### ISSUE THREAD

**Issue by MalikTH** [msikma/pokesprite#123]

**Comment by guitaristtom** [comment]
This would be awesome

**Comment by MalikTH** [comment]
I probably should have added more description, oops! This seems to do the trick, although I would also like a dark-colored variant as well. Those can be found in Pokemon HOME.

**Comment by koenigderluegner** [comment]
I don't have any professional tools to do image editing, but I could provide a simple inverted variant. For now I leave it to @msikma to decide and how to handle altered versions. (If the PR fulfills all requirements at all)

**Comment by sora10pls** [comment]
[Origin marks dumped from Pokémon HOME](https://github.com/msikma/pokesprite/files/8895578/icon_generation_color.zip) -- they store both white and colored variants of these textures.
