### ISSUE TITLE
Icons for complete and 10% zygarde forms and Ash-greninja

### ISSUE THREAD

**Issue by aloubelou** [msikma/pokesprite#16]
Hello,

Thanks a lot for all this work and sharing.
I noticed that some icons (regular and shinies) were missing for zygarde 10% form, zygarde complete form and Ash-greninja.

Is it already planned to add them ?

Best regards,
Alex

**Comment by msikma** [comment]
Thanks for letting me know, I must have simply missed them. I'll add them as soon as I have time.

**Comment by aloubelou** [comment]
My pleasure :)
I also noticed that the alola raticate does not appear in the full Icon overview. However it is present in the pokemon folder.

Thanks again for all your work.
Kind regards,
Alex

**Comment by msikma** [comment]
I'm glad you noticed this, let me know if you see anything else. There's so many icons, it's hard to get it all perfect 🙂

**Comment by msikma** [comment]
Fixed:

* Added Greninja-Ash icons
* Added Alola Raticate to the data file
* Added Zygarde icons

Thanks again. Let me know if you find anything else that's wrong.
