### ISSUE TITLE
Genesect forms

### ISSUE THREAD

**Issue by aloubelou** [msikma/pokesprite#17]
Hi msikma,

I noticed you added different forms for Silvally and Arceus, that's great !
Would it be possible to do the same thing for Genesect (with the different drives: Shock, Burn, Chill, Douse) ?

Unfortunately I'm not able to see the new icons you added on http://msikma.github.io/pokesprite/overview.html
Is it a refresh issue ?

Kind regards,
Alex

**Comment by msikma** [comment]
You're right that the overview hasn't been renewed yet, I'll do it as soon as I have some spare time. It needs to be rebuilt and redeployed, and I just didn't get around to it.

I'll add the Genesect icons, that's a good idea. Do you know if there are any other forms I've forgotten about?

**Comment by aloubelou** [comment]
I think you have pretty much every pokemons haha, but I'm not a pokemon expert :)
If I notice some other missing forms I'll ping you !

I know that solgaleo and Lunala have specific forms (radiant and full moon) but I'm not sure there are Icons for those 2.

**Comment by aloubelou** [comment]
Same thing for Mimikyu disguised and busted forms.
I saw you already have a thread for the pumpkaboo and gourgeist icons.

I just thought that we can dig also on the female pokemons like female pikachu (different tail), or female butterfree (a dark area on a wing), etc. but again, I'm not sure there are existing icons for them.

**Comment by msikma** [comment]
It's so easy to miss these variations. I do have female forms for everything—as far as I know. Keep 'em coming, let me know if you happen to stumble upon any others. But hopefully there should be very few missing icons!

**Comment by aloubelou** [comment]
Actually there are a lot of female with small differences but unfortunately they do not have dedicated official icons.
http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_gender_differences

**Comment by msikma** [comment]
Yeah, generally I don't add extra icons. Only the shiny versions. There have been a few exceptions.

**Comment by VictyLusi** [comment]
How is the sprite of 10% Forme Zygarde? I only can put 50% and complete Formes.

**Comment by msikma** [comment]
I've added the Genesect forms. A few missing right-facing icons were added. The other ones that were mentioned (e.g. Mimikyu busted) don't seem to have separate icons.
