### ISSUE TITLE
10% Zygarde Form

### ISSUE THREAD

**Issue by VictyLusi** [msikma/pokesprite#18]
How is the sprite of 10% Forme Zygarde? I only can put 50% and complete Formes.

**Comment by msikma** [comment]
I haven't updated the build yet. I'll do this as soon as possible...

Meanwhile, the file is there: https://github.com/msikma/pokesprite/blob/master/icons/pokemon/regular/zygarde-10-percent.png

**Comment by VictyLusi** [comment]
Ok thank you ^-^

**Comment by msikma** [comment]
You should see all the icons on the overview now:

http://msikma.github.io/pokesprite/build/overview.html
