### ISSUE TITLE
Difference between Male and Female

### ISSUE THREAD

**Issue by clad87** [msikma/pokesprite#21]
Hin i can't seen the difference between gender (cf. screenshot)

![2017-02-24_115259](https://cloud.githubusercontent.com/assets/1458019/23300870/d9fa689e-fa87-11e6-9b23-e12c89099265.png)

**Comment by msikma** [comment]
I'll double check the icons and fix the build, thanks for reporting!

**Comment by msikma** [comment]
I know I wasn't particularly fast, but check out the [overview](http://msikma.github.io/pokesprite/build/overview.html) now. It's working again.
