### ISSUE TITLE
Having issues when using Pokesprite with jQuery!

### ISSUE THREAD

**Issue by GiacomoLaw** [msikma/pokesprite#25]
Hi all

I'm having issues using Pokesprite with jQuery. When jQuery is enabled, all the mons show up as Bulbasaur. When disabled, it fixes itself and goes back to normal.

I am being affected on this repo: https://github.com/GiacomoLaw/pokefinder

I know that it is jQuery, as disabling it fixes the problem.

Thanks in advance!

**Comment by msikma** [comment]
Seems that the Pokesprite code is just totally wrong, it's attaching the methods to the global window object instead of to its own encapsulated object. One of the minified names just happens to be `$` by coincidence, so when jQuery is added to the mix it overrides the `$` on window.

I'll go and make some changes, maybe bring the JS into the year 2017 instead of 2011.

**Comment by msikma** [comment]
By the way...you typoed 'pikipek' as 'pipipek' somewhere in your code. 😄

**Comment by GiacomoLaw** [comment]
Okay, thanks!

**Comment by GiacomoLaw** [comment]
Do you know when it may come out? 😄

**Comment by msikma** [comment]
I'll work on it this weekend. You might also be able to [try this](https://gist.githubusercontent.com/msikma/ce3f98752786a8f2d75f9500fc85034e/raw/da2d85f235c1e56850029235de72dd79d7408bd3/pokesprite-tempfix.js) (untested), I've rewritten the existing code to use $$ as variable instead of $.

**Comment by GiacomoLaw** [comment]
Thank you very much!

**Comment by msikma** [comment]
The latest build is totally changed in terms of how it works (it's now a hybrid browser/Node/CommonJS/AMD module), could you give it a try and tell me if it works for you now?

**Comment by GiacomoLaw** [comment]
Sure, will do tomorrow! I presume I just update the .js and .css files?

Thanks so much!

**Comment by GiacomoLaw** [comment]
Awesome - it's working great! Thanks so much for the fix 😄

**Comment by msikma** [comment]
Glad that it works now!
