### ISSUE TITLE
[Feature Request] Add USUM icons

### ISSUE THREAD

**Issue by itsjavi** [msikma/pokesprite#34]
I know it is a bit early and probably you don't want to spoil yourself yet, but would be nice to add the icons for the new Pokemon and new forms in Ultra Sun and Moon

You can see them here (contains SPOILERS) : https://richi3f.github.io/pokemon-team-planner/

**Comment by msikma** [comment]
Hi there. I'd be glad to add them quickly, since I doubt there's that many to add. It wouldn't take that much time. I'm not entirely sure which icons are new, though... I'll ask around on Project Pokémon to see.

**Comment by msikma** [comment]
Can you check the latest update to see if all conforms to your expectations?

**Comment by itsjavi** [comment]
@msikma awesome work, thank you! it goes beyond my expectations :)
