### ISSUE TITLE
dex number slug not working

### ISSUE THREAD

**Issue by dominicbarnes** [msikma/pokesprite#36]
According to the docs and #2, I should be able to do something like:

```html
<span class="pkspr pkmn-004"></span>
```

But when I try to decorate the node, I just get the following warning message:

> Couldn't decorate icon with the following properties: { slug: "004", type: "pkmn" }

I thought maybe this was just a problem with the npm build, but I get the same issue on the overview page. You can reproduce this with a very big hack on the console there:

```js
document.body.innerHTML = '<span class="pkspr pkmn-004"></span>'
PkSpr.decorate(document.body)
```

**Comment by msikma** [comment]
I haven't tested that in a while. To be truthful, the JS code is very old and doesn't have unit tests, but I haven't had much time to replace it. I'll see if I can fix this.

**Comment by jameseilers** [comment]
I was just about to ask the same question. Any luck with a fix?

**Comment by msikma** [comment]
Apologies for the lack of an update. I'm going to resolve this either today or tomorrow—I've got a pretty short workday today, but I'm hoping to have it resolved anyway. I'm sure the problem isn't that hard to fix.

**Comment by msikma** [comment]
Strangely, it seems that the Closure Compiler is somehow mangling the input JS code in such a way that it breaks using regular numbers. I'll need to look at this more closely tonight.

**Comment by msikma** [comment]
Alright - could you try again with the latest build? I've updated to 1.5.1. I also updated the NPM package (forgot to do that for 1.5.0... oops.)

The problem was [some variables](https://github.com/msikma/pokesprite/commit/e38c47b9b864b31b7f916496abdaa7fcb5ec9a80) weren't being protected from name mangling.

**Comment by acassani91** [comment]
Working fine for me, thanks!

**Comment by dominicbarnes** [comment]
I'll take a look at this tonight! Thanks :)

**Comment by msikma** [comment]
Let me know if anything's wrong, assuming it works for now. 😊
