### ISSUE TITLE
Shiny Beautifly image not appearing

### ISSUE THREAD

**Issue by blitzpaw** [msikma/pokesprite#37]
The image for shiny Beautifly fails to load on a Google Spreadsheet when used as a function reading:

=image("https://raw.githubusercontent.com/msikma/pokesprite/master/icons/pokemon/shiny/beautifly.png")

Regular Beautifly works, however, and all other shiny and regular sprites seem to work.

**Comment by msikma** [comment]
It seems to work fine for me. The image is right there. How does the image load fail? Can you check the console or link to a spreadsheet where it fails?

**Comment by blitzpaw** [comment]
Appears to be working now, and I'm unable to replicate the issue. The image as used as the function above was previously not appearing, leaving just an empty cell. Swapping to other Pokemon or changing from shiny to regular worked as normal but for some reason, shiny Beautifly wasn't.

**Comment by msikma** [comment]
Likely a temporary network error. Let me know if it happens again though.
