### ISSUE TITLE
Glalite should be Glalitite

### ISSUE THREAD

**Issue by PC-Reviver** [msikma/pokesprite#42]
The image for Mega Glalie's mega stone is called "glalite" here. It should be "glalitite", according to the following sources:
- [https://bulbapedia.bulbagarden.net/wiki/Glalitite](https://bulbapedia.bulbagarden.net/wiki/Glalitite)
- [https://dex.pokemonshowdown.com/items/glalitite](https://dex.pokemonshowdown.com/items/glalitite)

**Comment by msikma** [comment]
Thanks for the report! I'm working on some changes to the project right now and I'll include this while I'm at it.
