### ISSUE TITLE
Shiny Naganadel error

### ISSUE THREAD

**Issue by Ammako** [msikma/pokesprite#43]
The icon for shiny Naganadel shows yellow wings, but it actually has black wings.

![Icon](https://raw.githubusercontent.com/msikma/pokesprite/master/icons/pokemon/shiny/naganadel.png)

![Image](https://serebii.net/Shiny/SM/804.png)

**Comment by msikma** [comment]
You're right, thanks for letting me know! I'll modify the sprite.

**Comment by msikma** [comment]
This looks better, right?

![naganadel](https://user-images.githubusercontent.com/1507745/45267928-a52a8280-b475-11e8-812b-db4aae51ba17.png)

**Comment by Ammako** [comment]
It does!

I don't know why it took me so long to notice the error, considering that I've been seeing that icon relatively frequently for the past few months, but here you go.

I love these btw. They make everything look so much better than using non-shiny icons.

**Comment by msikma** [comment]
Glad you like them 😄 
I've merged the new icon, will make a new release today when I have some time.
