### ISSUE TITLE
Old Amber? Also Thunder Stone error.

### ISSUE THREAD

**Issue by Enderwither02** [msikma/pokesprite#49]
I was looking through the fossils and I noticed that the Old Amber - the fossil that is used to revive Aerodactyl - is completely missing. Is it in a separate section, or was it simply forgotten?

Also, this may just be me, but the Thunder Stone sprite doesn't appear to be loading when I add it into a Google sheet. The other evolution items work just fine, but the Thunder Stone strangely isn't.

**Comment by msikma** [comment]
Old Amber is in key items: https://github.com/msikma/pokesprite/blob/master/icons/key-item/old-amber.png

The Thunder Stone is here: https://github.com/msikma/pokesprite/blob/master/icons/evo-item/thunder-stone.png

It's strange if it's not loading, but my guess would be that it's a temporary resolution error. Any chance you could reproduce by making a Google Sheet and linking me to it?

**Comment by Enderwither02** [comment]
Alright, thanks. I tried reproducing the Thunder Stone issue but it decided to actually start working, so I'm wondering if I had typed something in wrong when I typed out the URL.

**Comment by msikma** [comment]
I'll still duplicate Old Amber since that's a good idea. Can't say when I'll have time for it though, since I'm traveling for work right now...

**Comment by Enderwither02** [comment]
That sounds like it must be awful. At least, depending on the career.

**Comment by msikma** [comment]
This has been updated in the in-progress Sword/Shield update.
