### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by dreamy-donno** [msikma/pokesprite#51]
Sprites for half of the Pokemon starting with the letter V and then through to Z are missing.

**Comment by 5310** [comment]
I assume you're browsing them on the web. GitHub has a limit on how many files it can list inside a single folder. They're just getting truncated on the frontend, [the files very much still exist](https://github.com/msikma/pokesprite/blob/master/icons/pokemon/regular/zygarde.png).

![Screenshot_2019-05-16_09-18-27](https://user-images.githubusercontent.com/112914/57825261-b45b9000-77bb-11e9-9d8b-abaaa2b43e04.png)

**Comment by msikma** [comment]
Thanks for clearing it up @5310 🙂

Indeed the files are still there, it's just that there are a lot of them.
