### ISSUE TITLE
I made DexTool and it uses PokéSprite

### ISSUE THREAD

**Issue by PoshoDev** [msikma/pokesprite#58]
Hello,

I made a [DexTool](https://github.com/PoshoDev/DexTool) in order to help people manage their Pokémon living dexes with the correct box ordering. It also has features for shiny living dexes, image exporting, encounter counting and output for streaming services.

All of the Pokémon sprites are from PokéSprite, so I thought you'd like to know.

**Comment by msikma** [comment]
Cool 🙂 I added this to the list of related projects.

**Comment by PoshoDev** [comment]
Thankssss.
