### ISSUE TITLE
Gender differences not working

### ISSUE THREAD

**Issue by Josephvb10** [msikma/pokesprite#6]
As you can see on the compiled overview in this repo and when you try to compile it for yourself, gender differences are not working at all.

**Comment by msikma** [comment]
Seem to have missed that completely! Thanks for reporting, I'll have a look at this later today.

**Comment by msikma** [comment]
This has been fixed. Thanks again for reporting it. It's amazing to me now how old-fashioned this code is, I'll have to update it.
