### ISSUE TITLE
Gigantamax Charizard shiny colors seem not accurate

### ISSUE THREAD

**Issue by route1rodent** [msikma/pokesprite#60]
It seems that the original is more purple rather than gray.
Here is a comparison (pokesprite VS HOME shiny render):

<img width="925" alt="Screenshot 2020-03-09 at 01 01 06" src="https://user-images.githubusercontent.com/18262122/76173688-e0f4f400-61a1-11ea-909a-4c8c7ef426b7.png">

**Comment by msikma** [comment]
Thanks. I'll change it. The gmax forms were the most difficult to make because all the screenshots I could find had that red glow that made it hard to pick the exact colors.

**Comment by route1rodent** [comment]
thanks. you can find them here, ripped from home: https://www.spriters-resource.com/nintendo_switch/pokemonhome/

**Comment by msikma** [comment]
New version:

![charizard-gmax](https://user-images.githubusercontent.com/1507745/76238729-95d5f200-6230-11ea-814c-bea86d9d8600.png)

**Comment by route1rodent** [comment]
looks good 👍
