### ISSUE TITLE
Gen8 icons aren't aligned the same

### ISSUE THREAD

**Issue by Kanimi** [msikma/pokesprite#62]
Please see the following two examples: 
https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/regular/grookey.png
https://raw.githubusercontent.com/msikma/pokesprite/master/icons/pokemon/regular/pikachu.png

As you can see the grookey sprite seems to have extra space which can be seen easily if you copy image and paste it next to gen 1-7 ones in paint - https://prnt.sc/rfqcsf

This causes Pokemon to not be aligned and not displaying properly in tabs as seen here:  https://tinyurl.com/Kanimi-Pokemon

Any reason for the extra space on the new sprites?

Also unless I am blind there's no koffing-galar or weezing-galar.

**Comment by msikma** [comment]
There are actually three different sets:

* Legacy (old Gen 7 in old format), in `/icons`
* Gen 7 updated to Gen 8 specs, in `/pokemon-gen7`
* Gen 8, in `/pokemon-gen8`

When developing applications using these icons, you should preferably use `/pokemon-gen8` only. You can simply use: https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/regular/pikachu.png which is the correct size.

The old `/icons` directory is only for legacy support. These icons are 40x30, while in Gen 8 the icons have been updated to 68x56.

Koffing-galar does not exist, but weezing-galar is here: https://github.com/msikma/pokesprite/blob/master/pokemon-gen8/shiny/weezing-galar.png - it's only available in the new Gen 8 set.

**Comment by Kanimi** [comment]
Would you know then why some of the Pokemon sprites are not showing up at all? Especially having replaced the legacy icons with the new ones.
![pokemon](https://user-images.githubusercontent.com/48927055/76795868-26c54400-67c2-11ea-800b-88e0192226d6.png)

**Comment by msikma** [comment]
I'm not sure. However, the legacy `/icons` directory contains both inventory items and Pokémon, and the new `/pokemon-gen7x` and `/pokemon-gen8` directories *only* contain Pokémon, so you need to make sure to remove the extra `/pokemon/` section from the URL if you're replacing it. I suggest you double check the URLs in your app/sheet.

For example, Seel and Hitmonchan and others are missing from your image, but they're there:

* https://github.com/msikma/pokesprite/blob/master/pokemon-gen8/regular/seel.png
* https://github.com/msikma/pokesprite/blob/master/pokemon-gen8/regular/hitmonchan.png

**Comment by coltongit** [comment]
Agreed. This isn't actually an issue with pokesprite, but with your particular deployment of it. This can therefore be closed

**Comment by msikma** [comment]
Just had another look at the spreadsheet, looks like it's working now? Let me know if anything else comes up, I don't mind having a look.
