### ISSUE TITLE
[SWSH] Dhelmise Shiny Sprite

### ISSUE THREAD

**Issue by sora10pls** [msikma/pokesprite#66]
![image](https://www.serebii.net/Shiny/SWSH/781.png) ![image](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/shiny/dhelmise.png)

As you can see in the above comparison, the wooden part of the anchor remains brown when Shiny.

The Gen 7 sprite correctly replicates the official coloration: ![image](https://raw.githubusercontent.com/msikma/pokesprite/master/icons/pokemon/shiny/dhelmise.png)

**Comment by msikma** [comment]
Thanks for reporting! I'll go fix it in a minute.

**Comment by msikma** [comment]
Changed the anchor to be wooden again, and I also adjusted the pink part a bit since it didn't look too good. I also made the eye yellow again.

![dhelmise](https://user-images.githubusercontent.com/1507745/77234009-9add5e80-6bab-11ea-9abc-68d4ab888a1b.png)

**Comment by msikma** [comment]
I'm assuming it's ok now, so just merged it.
