### ISSUE TITLE
Shiny changes as of Pokémon Home

### ISSUE THREAD

**Issue by msikma** [msikma/pokesprite#73]
[Apparently](https://www.polygon.com/2020/2/14/21138148/pokemon-home-shiny-models-new-sprites-3d-artwork-nintendo-switch-castform-minior-magearna), as of Pokémon Home, the following shiny Pokémon changed designs:

* [Castform's rainy, snowy and sunny forms](https://twitter.com/Jackson556D/status/1227598163109982208)
* [Minior](https://twitter.com/PLDHnet/status/1227445555070144513?ref_src=twsrc%5Etfw) (now each color has a unique shiny)
* [Magearna](https://twitter.com/KageGengar/status/1227849779520196609), which actually already had shiny versions, but that version was never officially obtainable

I'm not sure if this is a full list. Anybody know of other changes besides these?

For Minior and Magearna, I think we should make a copy of their current shiny sprites and name them "gen7" (or maybe "original"?) so that we can keep the images around, and then add the new versions. [PP doesn't seem to have all Minior images yet, though, so we might need more screenshots.](https://projectpokemon.org/docs/spriteindex_148/home-sprites-gen-7-r134/)

Thanks to Wordeur for alerting me to this by email.

**Comment by msikma** [comment]
Reference:

<table>
<tr>
<th>#</th><th>Pokémon</th><th>Original</th><th>New</th>
</tr>
<tr>
<td>801</td>
<td>Magearna</td>
<td><img src="https://projectpokemon.org/images/sprites-models/homeimg/poke_capture_0801_000_uk_n_00000000_f_n.png" width="100" /></td>
<td><img src="https://projectpokemon.org/images/sprites-models/homeimg/poke_capture_0801_000_uk_n_00000000_f_r.png" width="100" /></td>
</tr>
<tr>
<td>774</td>
<td>Minior (Red)</td>
<td><img src="https://user-images.githubusercontent.com/1507745/80385256-24b4d180-88a6-11ea-97d2-036a81abb6ef.png" width="100" /></td>
<td><img src="https://projectpokemon.org/images/sprites-models/homeimg/poke_capture_0774_007_uk_n_00000000_f_r.png" width="100" /></td>
</tr>
<tr>
<td>774</td>
<td>Minior (Orange)</td>
<td><img src="https://user-images.githubusercontent.com/1507745/80385256-24b4d180-88a6-11ea-97d2-036a81abb6ef.png" width="100" /></td>
<td>?</td>
</tr>
<tr>
<td>774</td>
<td>Minior (Yellow)</td>
<td><img src="https://user-images.githubusercontent.com/1507745/80385256-24b4d180-88a6-11ea-97d2-036a81abb6ef.png" width="100" /></td>
<td>?</td>
</tr>

<tr>
<td>774</td>
<td>Minior (Green)</td>
<td><img src="https://user-images.githubusercontent.com/1507745/80385256-24b4d180-88a6-11ea-97d2-036a81abb6ef.png" width="100" /></td>
<td>?</td>
</tr>

<tr>
<td>774</td>
<td>Minior (Blue)</td>
<td><img src="https://user-images.githubusercontent.com/1507745/80385256-24b4d180-88a6-11ea-97d2-036a81abb6ef.png" width="100" /></td>
<td>?</td>
</tr>
<tr>
<td>774</td>
<td>Minior (Indigo)</td>
<td><img src="https://user-images.githubusercontent.com/1507745/80385256-24b4d180-88a6-11ea-97d2-036a81abb6ef.png" width="100" /></td>
<td>?</td>
</tr>
<tr>
<td>774</td>
<td>Minior (Violet)</td>
<td><img src="https://user-images.githubusercontent.com/1507745/80385256-24b4d180-88a6-11ea-97d2-036a81abb6ef.png" width="100" /></td>
<td>?</td>
</tr>
<tr>
<td>351</td>
<td>Castform (Rainy)</td>
<td><img src="https://projectpokemon.org/images/sprites-models/homeimg/poke_capture_0351_002_mf_n_00000000_f_n.png" width="100" /></td>
<td><img src="https://projectpokemon.org/images/sprites-models/homeimg/poke_capture_0351_002_mf_n_00000000_f_r.png" width="100" /></td>
</tr>
<tr>
<td>351</td>
<td>Castform (Sunny)</td>
<td><img src="https://projectpokemon.org/images/sprites-models/homeimg/poke_capture_0351_001_mf_n_00000000_f_n.png" width="100" /></td>
<td><img src="https://projectpokemon.org/images/sprites-models/homeimg/poke_capture_0351_001_mf_n_00000000_f_r.png" width="100" /></td>
</tr>
<tr>
<td>351</td>
<td>Castform (Snowy)</td>
<td><img src="https://projectpokemon.org/images/sprites-models/homeimg/poke_capture_0351_003_mf_n_00000000_f_n.png" width="100" /></td>
<td><img src="https://projectpokemon.org/images/sprites-models/homeimg/poke_capture_0351_003_mf_n_00000000_f_r.png" width="100" /></td>
</tr>
</table>

**Comment by WordeurFTB** [comment]
I think the pictures of Pokémon HOME shows differences on Marshadow.
![poke_capture_0802_000_uk_n_00000000_f_n](https://user-images.githubusercontent.com/23153824/80624524-12749800-8a4c-11ea-8efc-1306715f6054.png)
![poke_capture_0802_000_uk_n_00000000_f_r](https://user-images.githubusercontent.com/23153824/80624537-19030f80-8a4c-11ea-8ec7-7c59cd9030b5.png)
The shiny version is slightly lighter : skin (or fur ?) and the shadows are made of a lighter gray and the eyes are made of a lighter orange.
When the respective icons from this project shows difference in the strand of hair :
![marshadow](https://user-images.githubusercontent.com/23153824/80624991-cd049a80-8a4c-11ea-84e6-cbaf601b97cd.png)
![marshadow (1)](https://user-images.githubusercontent.com/23153824/80625002-d0982180-8a4c-11ea-9197-07af67b18485.png)
Unfortunately I didn't found the "z-move mode" graphics of HOME (if they even exist) but in the 3DS games they showed a more blatant difference :
![Shiny_Marshadow_Comparison](https://user-images.githubusercontent.com/23153824/80625181-2076e880-8a4d-11ea-9c79-7c5031526453.png)

Sources :
https://projectpokemon.org/docs/spriteindex_148/
https://bulbapedia.bulbagarden.net/wiki/Main_Page

**Comment by msikma** [comment]
Hi all. It's been a while.

I've not yet made any change to Marshadow yet but I've got a first version of the others:
<table>
<tr>
<th>Name</th>
<th>Regular</th>
<th>New shiny</th>
<th>Old shiny</th>
</tr>

<tr>
<td>Minior blue</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/minior-blue.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-blue.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-blue.png"></td>
</tr>

<tr>
<td>Minior green</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/minior-green.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-green.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-green-gen7.png"></td>
</tr>

<tr>
<td>Minior indigo</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/minior-indigo.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-indigo.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-indigo-gen7.png"></td>
</tr>

<tr>
<td>Minior orange</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/minior-orange.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-orange.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-orange-gen7.png"></td>
</tr>

<tr>
<td>Minior red</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/minior-red.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-red.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-red-gen7.png"></td>
</tr>

<tr>
<td>Minior violet</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/minior-violet.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-violet.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-violet-gen7.png"></td>
</tr>

<tr>
<td>Minior yellow</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/minior-yellow.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-yellow.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/minior-blue-gen7.png"></td>
</tr>

<tr>
<td>Castform rainy</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/castform-rainy.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/castform-rainy.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/shiny/castform-rainy.png"></td>
</tr>

<tr>
<td>Castform sunny</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/castform-sunny.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/castform-sunny.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/shiny/castform-sunny.png"></td>
</tr>

<tr>
<td>Castform snowy</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/castform-snowy.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/castform-snowy.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/shiny/castform-snowy.png"></td>
</tr>

<tr>
<td>Magearna</td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/regular/magearna.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/magearna.png"></td>
<td><img src="https://raw.githubusercontent.com/msikma/pokesprite/pokemon-home/pokemon-gen8/shiny/magearna-gen7.png"></td>
</tr>

</table>

**Comment by msikma** [comment]
I just wanted to add, the Minior ones look just a little bit off from the Home images. But I think this is better because this way they're closer to the non-shiny sprites. A lot of sprites are actually just a tiny bit different from the model because the colors tend to be much more saturated and sometimes tiny details are left out due to the size (like the "sprinkles" on Minior).

**Comment by msikma** [comment]
Updates have been merged.
