### ISSUE TITLE
Sprites with transparent pixels trimmed?

### ISSUE THREAD

**Issue by martimlobao** [msikma/pokesprite#75]
Wondering if it's possible to have the new sprites with the transparent pixels cropped out. I understand that having them all conform to a standard of 68 by 56 pixels makes sense for a lot of use cases, but trying to use them in Google Sheets makes a lot of sprites tiny and hard to see.

For example, Grookey's actual height is about 25 pixels, but since the image height is 56, it shrinks down to half the size of the row. On the other hand, Eternatus's Eternamax form takes up the entire 56 pixels, so it's also not possible to simply crop all sprites to half the height in Google Sheets.

Image cropped to actual sprite height (taken from [serebii.net](https://www.serebii.net/pokedex-swsh/icon/810.png)):
<img width="344" alt="Screen Shot 2020-06-15 at 18 45 00" src="https://user-images.githubusercontent.com/6430786/84689132-6d007f80-af38-11ea-83f3-882fc250c13e.png">
Sprites in 68x56 box:
<img width="343" alt="Screen Shot 2020-06-15 at 18 45 20" src="https://user-images.githubusercontent.com/6430786/84689151-72f66080-af38-11ea-89ba-7ce27767042e.png">

**Comment by msikma** [comment]
This is a good point and it would also help people trying to center the sprites vertically, rather than having them appear "on the ground".

I'm open to the idea, and it wouldn't be too hard to do since I can just run the trim filter on every file. I'll look into it.

**Comment by Knightinkodes** [comment]
Just a note, when using Google Sheets in a PC in edit mode or view mode, but not published, sprites become blurred if they are centered vertically or horizontally and have "mismatched" size with the cell width or height. So, if the point of cropping the sprites would be for Sheets usage only, it would be better if all the new sprites have all even or all odd number of pixels for width and height.

**Comment by msikma** [comment]
Now that the DLC update is done, it's time to look into this again. I'm thinking it might be a good idea to make a special fork of this project with trimmed sprites, that way this repo can remain simple.

**Comment by atmize1027** [comment]
Please unsubscribe me from this thread's notifications. Thank you.

**Comment by msikma** [comment]
@atmize1027, unfortunately I can't unsubscribe you, the only way for that to happen is for you to unsubscribe yourself.

**Comment by martimlobao** [comment]
Implemented in separate fork here: https://github.com/martimlobao/pokesprite
