### ISSUE TITLE
Add new sprites for Pokémon and items from Sword/Shield Expansion Pass

### ISSUE THREAD

**Issue by msikma** [msikma/pokesprite#76]
Today the Sword/Shield Expansion Pass came out, containing [these new sprites](https://twitter.com/mattyoukhana_/status/1273285719960752130) and some new item sprites too.

I've received a clean copy of the sprites and I've started incorporating them into the project.

**Comment by koenigderluegner** [comment]
Hello msikma, I know I'm very early asking this but do you know how you will name Urshifu as a slug? His two forms are Single Strike Style and Rapid Strike Style - Single strike considered "Base form".
Trying to follow your old conventions I prepared my spreadsheet naming them 

urshifu
urshifu-rapid-strike

They both have "Strike Style" at the end, so I'm not sure which part you might scrap.

Other than that if you need help again mapping some items or whatever, feel free to ping me :)

**Comment by msikma** [comment]
Thanks for offering your help!

I have to agree, just like Oricorio I prefer to simplify the names a bit and remove "style" at the end here, but it's also not something I feel very strongly about so if there's a good argument for keeping the full form name I'd be happy to do that too. The main reason is I want the filenames to not be too long since most people access the files directly by filename.

I still want to try and offer as much compatibility with other major projects as possible with regard to form names, by offering a lookup table for the other standards, but for now the way you suggested is fine.

**Comment by koenigderluegner** [comment]
they have different gmax versions, one's blue and one's red (different icons in-game) I predicted the slugs as urshifu-gmax and urshifu-rapid-strike-gmax, icons can be seen [here](https://twitter.com/mattyoukhana_/status/1273292610413748230)

**Comment by Knightinkodes** [comment]
Darmanitan seems to be the only case with 2 forms "together". If the pattern used for Darmanitan is used, I believe slugs would be urshifu, urshifu-rapid-strike, urshifu-single-strike-gmax and urshifu-rapid-strike-gmax.

**Comment by koenigderluegner** [comment]
i think its more like toxtricity where basic form (amped) is just toxtricity or toxtricity-gmax and low-key form is toxtricity-low-key or toxtricity-low-key-gmax

**Comment by Knightinkodes** [comment]
Ah, I thought Toxtricity was handled differently because it has the same sprite for both gmax forms and the repo only has toxtricity-gmax being used.

Btw, why are appletun-gmax and toxtricity-low-key-gmax not being used as placeholders?

**Comment by koenigderluegner** [comment]
They don't have different sprites but different slugs as an option in pokemon.json as forms

**Comment by msikma** [comment]
Just wanted to give a brief update that I've started on the changes. Fortunately there's not that many new sprites. I hope to have a branch with all the changes in a few days for testing.

**Comment by itsjavi** [comment]
I opened this accidentally because I didn't notice this issue, but I did some research on where to find the icons, if it can be useful for you: https://github.com/msikma/pokesprite/issues/79

**Comment by thegreenkacheek** [comment]
Just for fun (and maybe if you haven't gotten to some of them yet) I made shiny sprites for all the DLC forms!  Please feel free to use these in the project if it saves you work! https://imgur.com/a/u90mvjl

**Comment by msikma** [comment]
Update. I'm nearly finished with the sprite work. Only the new Galar Pokémon are left, which I'll do tomorrow. Everything else has been done.

The only thing left after that is to add them to the JSON file and test the changes. It'd be nice if people could have a look at the sprites too, to make sure I didn't make any mistakes. I actually found a small mistake in the Inteleon sprite from last update.

<img width="580" alt="Screenshot 2020-07-06 at 00 33 31" src="https://user-images.githubusercontent.com/1507745/86543604-7cb02a00-bf20-11ea-8154-0e7035e75edb.png">

I'll update the JSON tomorrow.

> Just for fun (and maybe if you haven't gotten to some of them yet) I made shiny sprites for all the DLC forms! Please feel free to use these in the project if it saves you work! https://imgur.com/a/u90mvjl

Nice work, these look really good. And you got to them really quickly too! The only thing is, I prefer to do my own versions, since I want to make absolutely sure that the sprites I make are exactly consistent with my own previous work. And, well, it would feel strange to not do 100% of them now that I've done like 99% of them already. But that's really good work and I'll be sure to consult these if I can't figure out the last few sprites tomorrow.

**Comment by koenigderluegner** [comment]
I would love to help! Is it possible to put the new sprites into a combined image for easier checks?

**Comment by msikma** [comment]
Did the last sprites and a bit more checking, here's a list of the new sprites: https://github.com/msikma/pokesprite-gen8-new-icons/wiki/Gen-8-DLC-new-sprites - feel free to let me know if anything should be changed.

Tomorrow I'll add all this to the JSON file, and finalize the items sprites.

One thing is that's really weird is that the items seem to be in double resolution with the white outline around the sprites being twice the regular resolution. Normally the items are displayed at 2x size, with the white outline being as blocky as the pixel art itself. I'm making sure the new item sprites are consistent with the old sprites.

**Comment by sora10pls** [comment]
Great work on all of the sprites! The only inconsistency I really noticed was with Shiny Zarude. The belly is basically spot-on, but the sprites you have listed use the same brown for the eyes. If you look at the official HOME renders I’ve posted, you’ll see that the eyes are actually different between nonshiny/shiny, though they don’t use the same brown; it’s a little bit brighter in comparison.

Context: https://twitter.com/mattyoukhana_/status/1273241333864505345

Other than that, I can’t find anything else myself. 👍

**Comment by koenigderluegner** [comment]
I checked every sprite against the models from HOME, the models from HOME look a bit brighter/less saturated than those sprites, but I think it's just the lightning/shading on those renders so I don't see a problem here. There is one exception though, Heracross in HOME looks quite than your new shiny sprite (also a litttle bit lighter in-game):

![image](https://user-images.githubusercontent.com/25096024/86615102-4c19d000-bfb4-11ea-8676-887887842928.png)

Other than that, theres nothing to "complain" about, really well done!

**Comment by msikma** [comment]
You're right, and maybe Sharpedo also looks a tiny bit too saturated. 

Part of the problem is that I only just noticed they look slightly different in Photoshop because they're supposed to be displayed in srgb mode, but it's not. That made it more saturated than it should be. I'm gonna have to have another look at that. But aside from that it should be a bit brighter.

Regarding Zarude, you are right. Actually, I was a bit conflicted about this, because GF's original non-shiny box sprite also has no brightness variation between top and bottom:

![poke_icon_0988_00n_n](https://user-images.githubusercontent.com/1507745/86645033-54870080-bfde-11ea-8d83-e41b9354ade9.png)

Since that's how the original was, I just kept the same contrast. But I'm going to see how it looks if I modify the shiny one to have a brighter face and less bright chest.

**Comment by msikma** [comment]
See pull #80.

I can't get a new version of the docs up without actually merging (since it can only host docs from the `master` branch) but here's a copy of the docs with the changes: https://doubla.de/pokesprite/overview/dex-gen8-new.html - note that the menu links don't work here, they go to the old version. So here you can have another look at the sprites.

ps, @koenigderluegner, this version shows `gmax-rapid-strike` instead of `rapid-strike-gmax` but I've already fixed that in the JSON file.

**Comment by koenigderluegner** [comment]
I just went through the pull request, I noticed you named the new Cap-Pikachu Galar-Cap, I think the official (=datamined) name is World-Cap, Serebii has it too:
![image](https://user-images.githubusercontent.com/25096024/86821937-4511c100-c08b-11ea-9271-9bdc518a84ad.png)

Also the provided link is missing some new pokemon (was looking for heracross and scizor, both were missing) so I checked them straight out of the request, heracross seems to be lighter now, more like the render (if I'm not crazy), which is good!

**Comment by itsjavi** [comment]
also worth mentioning that it seems that Magearna got a new shiny color pattern in Home. https://twitter.com/Kaphotics/status/1227417320064081920/photo/1

**Comment by koenigderluegner** [comment]
@itsjavi already taken care of, see [magearna shiny sprite](https://github.com/msikma/pokesprite/blob/b0d8ceb5078570301bf089fdc0748465ffbfd82b/pokemon-gen8/shiny/magearna.png)

**Comment by msikma** [comment]
> I just went through the pull request, I noticed you named the new Cap-Pikachu Galar-Cap, I think the official (=datamined) name is World-Cap, Serebii has it too:

Thanks, will change that.

**Comment by msikma** [comment]
I haven't been able to play Sword/Shield much yet, let alone the DLC. Does anyone know if Sandslash-Alola is available? It's just weird to me that they updated Sandslash's icon, but not Sandslash-Alola's icon. I can see the [Alola model](https://www.serebii.net/pokedex-swsh/sandslash/) on Serebii, though.

I'm also seeing now that the new World Cap Pikachu is moved up and to the right a little bit. A few other sprites (like Venusaur) have been moved around to center them better. I'm updating all other Pikachu sprites to follow suit.

**Comment by sora10pls** [comment]
Sandslash, Exeggutor and Marowak are all in DLC 1, including their Alolan Forms. They just didn’t update its sprite like with the other Alolan Forms in base SWSH.

**Comment by msikma** [comment]
Here's a new version of the overview, with this time all new sprites correctly tagged so they show up:

https://doubla.de/pokesprite/overview/dex-gen8-new.html

Urshifu rapid-strike-gmax is visible now too.

**Comment by koenigderluegner** [comment]
I quickly checked over the new overview, in my opinion it good to go! great work

**Comment by msikma** [comment]
There's one more thing: where should the items be put in?

We've got these:

```
item_1584  armor-pass.png
item_1588  armorite-ore.png
item_1587  exp-charm.png
item_1582  galarica-cuff.png
item_1581  galarica-twig.png
item_1589  mark-charm.png
item_1579  max-honey.png
item_1580  max-mushrooms.png
item_1586  rotom-bike-black.png
item_1585  rotom-bike-white.png
item_1583  style-card.png
```

Also, does the `rotom-bike-black`/`rotom-bike-white` replace the old `rotom-bike-2` in Key Items that's currently there?

**Comment by sora10pls** [comment]
@msikma Any particular reason for the female Cap Pikachu sprites? Their ingame personal data has them set to be male only (like Gallade, Tauros etc).

**Comment by msikma** [comment]
> Any particular reason for the female Cap Pikachu sprites? Their ingame personal data has them set to be male only (like Gallade, Tauros etc).

No reason, I'm aware that they can't be female. Figured I might as well do it anyway.

**Comment by sora10pls** [comment]
Fair enough! Also to answer your question about the Rotom Bike, it doesn't replace it.

1081 = Land Mode
1266 = Water Mode (upgraded)
1585 = White
1586 = Black

The player can only have 1 at a time.

**Comment by msikma** [comment]
Ah I see, so you first upgrade it to Water Mode, and after that you can optionally upgrade it to one of the black/white variants?

**Comment by sora10pls** [comment]
Correct! It also automatically applies all boost upgrades for the Bike as well if you choose to upgrade to White/Black.

**Comment by msikma** [comment]
The old Rotom bike sprites are named `rotom-bike-1` and `rotom-bike-2` since I didn't know they were called Land/Water. Thinking about naming them `rotom-bike-land`, `rotom-bike-water`, `rotom-bike-white`, `rotom-bike-black`. I doubt anyone would be inconvenienced by the old sprite changing name at this point, since even PKHeX doesn't use it.

**Comment by koenigderluegner** [comment]
> item_1584  armor-pass.png
> item_1588  armorite-ore.png
> item_1587  exp-charm.png
> item_1582  galarica-cuff.png
> item_1581  galarica-twig.png
> item_1589  mark-charm.png
> item_1579  max-honey.png
> item_1580  max-mushrooms.png
> item_1586  rotom-bike-black.png
> item_1585  rotom-bike-white.png
> item_1583  style-card.png

I currently have those slugs: 

medicine/max-honey
battle-item/max-mushrooms
other-item/galarica-twig
evo-item/galarica-cuff
key-item/style-card
key-item/armor-pass
key-item/rotom-bike-3
key-item/rotom-bike-4
key-item/exp-charm
other-item/armorite-ore
key-item/mark-charm

Item name itself are guesses (like rotom bikes) but the categories are matched with the games

**Comment by msikma** [comment]
Thanks for helping out again in this regard, I ended up not renaming the Rotoms since it doesn't really matter that much what they're named. I've placed [the DLC items](https://github.com/msikma/pokesprite/pull/80/commits/c173205d12b12ac3d4ae6eb17e8b5f3f81e3676c) under the categories you mentioned.

I've updated the temp docs. [The Gen 8 (new)](https://doubla.de/pokesprite/overview/dex-gen8-new.html) and [Gen 8](https://doubla.de/pokesprite/overview/dex-gen8.html) (here you can see all the new Pikachu sprites), and finally the [inventory list](https://doubla.de/pokesprite/overview/inventory.html). All new DLC inventory items are there, with and without outline.

I think that's about it? There are a few other things: #77 and #78. I'll go and fix that tomorrow so that it's in the next release too. Should be quick to do.

**Comment by sora10pls** [comment]
Thanks for all your work, @msikma! End result with the sprites is spot on.

**Comment by msikma** [comment]
Last update. Added the "marks" (a type of ribbon introduced in the DLC), plus the shiny leaf/leaf crown from HGSS, and the Gigantamax icon.

Final changes:

* https://doubla.de/pokesprite/overview/dex-gen8-new.html
* https://doubla.de/pokesprite/overview/inventory.html
* https://doubla.de/pokesprite/overview/misc.html

Also updated the readme and things, so I'll put it live tomorrow.

**Comment by itsjavi** [comment]
@msikma any chance to get the mega evolution icon back too? since now we have the dynamax one

**Comment by msikma** [comment]
> @msikma any chance to get the mega evolution icon back too? since now we have the dynamax one

@itsjavi I assume you mean this old one?

![ball-mega](https://user-images.githubusercontent.com/1507745/87230810-6a1b7200-c3b2-11ea-99ca-be15352150fc.png)

Currently the project does have this icon:

![mega](https://user-images.githubusercontent.com/1507745/87230833-8ae3c780-c3b2-11ea-83c3-233d0e221ad7.png)

It's under `pokemon-gen8/mega.png`. This is the icon that gets overlaid on top of a regular Pokémon sprite to indicate it's Mega Evolved. That's why it's under the Pokémon directory, since it's the same size as a box sprite and goes with it.

I don't mind having an extra Mega Evolution icon under the misc section but maybe there's a better one than that really tiny one from the X/Y battle interface?

**Comment by itsjavi** [comment]
ah ok yes, I was trying to find it under misc.
I think we don't have a better one unless the one from Let's Go is better.

**Comment by msikma** [comment]
Well, there is the Key Stone from Let's Go:

![item_0773](https://user-images.githubusercontent.com/1507745/87230992-b1eec900-c3b3-11ea-95d6-ad17a0982065.png)

But that one's almost identical to the `mega.png` I linked, slightly smaller even when you remove the ring around it.

Unfortunately I don't have a copy of UI element rips from Let's Go so I don't know if there's anything better in there but I'll have a look and see if I can find something. I could also just crop the `mega.png` one and we could use that?

**Comment by msikma** [comment]
Any thoughts on this?

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/1507745/87231241-b3b98c00-c3b5-11ea-873e-67a5a5e3ccfb.png">

There is a very nice bigger one in Pokémon Tretta: https://bulbapedia.bulbagarden.net/wiki/File:Tretta_Mega_Evolution_icon.png

**Comment by msikma** [comment]
Or maybe this. This is the Tretta one but I've adapted it so it's the same size as the pixel art one, albeit retina ready (2x).

![mega-evolution-sigil-hires](https://user-images.githubusercontent.com/1507745/87231753-29bff200-c3ba-11ea-9125-5c63a04d0989.png)

This might be useful since it's higher resolution, even though it's an edited icon.

**Comment by msikma** [comment]
I ended up adding three Mega Evolution icons.

All is merged now! Thanks everyone for helping out with tagging and error checking. 🙂
