### ISSUE TITLE
Shiny Leaf, Leaf Crown, and Gigantamax symbol?

### ISSUE THREAD

**Issue by guitaristtom** [msikma/pokesprite#77]
These aren't exactly items, but it would be awesome if you could add in the assets for the shiny leaf and shiny crown from HGSS: 
https://serebii.net/heartgoldsoulsilver/shinyleaf.shtml
https://bulbapedia.bulbagarden.net/wiki/Shiny_Leaf

Also having the Gigantamax symbol would be pretty nice. Maybe the three of these could go in the misc section like the ribbons are?

**Comment by msikma** [comment]
All three of these are included in the update for Sword/Shield (#80).

**Comment by guitaristtom** [comment]
Nice. Thank you!
