### ISSUE TITLE
Sword and Shield Mark "ribbons"?

### ISSUE THREAD

**Issue by guitaristtom** [msikma/pokesprite#78]
Adding in marks would be handy, but _personally_ I believe that they should go in to their own folder in the misc section, not lumped in with ribbons like Serebii does it...

https://www.serebii.net/swordshield/marks.shtml
https://www.serebii.net/games/ribbons.shtml

**Comment by msikma** [comment]
Thanks for letting me know about this. And I agree, they should be in their own section.

**Comment by msikma** [comment]
@guitaristtom would you happen to know if there are any new ribbons as of the DLC?

I've just taken all marks + their data from this page and I'll be adding them separately from the ribbons, in the misc section, but I'm just wondering now if there are new ribbons to add too while I'm at it.

**Comment by koenigderluegner** [comment]
@msikma i checked the ribbons list, i was looking for galar champion ribbon and didnt see it (at least not under galar-XXX) when was the last time you added ribbons? are sword/shield ribbons there using different names?

**Comment by msikma** [comment]
The Galar champion ribbon is under `misc/ribbon/gen8/galar-champion-ribbon.png`. I put those in a separate directory because they're 128x128 while the others are 40x40.

**Comment by msikma** [comment]
The marks have been added to #80.

**Comment by msikma** [comment]
Last update. Added the "marks" (a type of ribbon introduced in the DLC), plus the shiny leaf/leaf crown from HGSS, and the Gigantamax icon.

Final changes:

* https://doubla.de/pokesprite/overview/dex-gen8-new.html
* https://doubla.de/pokesprite/overview/inventory.html
* https://doubla.de/pokesprite/overview/misc.html

Also updated the readme and things, so I'll put it live tomorrow.

**Comment by guitaristtom** [comment]
> @guitaristtom would you happen to know if there are any new ribbons as of the DLC?
> 
> I've just taken all marks + their data from this page and I'll be adding them separately from the ribbons, in the misc section, but I'm just wondering now if there are new ribbons to add too while I'm at it.

Sorry, I have been AFK for a few days. 

From my knowledge no new ribbons or marks were added to the DLC (at least with IoA).
