### ISSUE TITLE
New Icons from the Isle of Armor DLC

### ISSUE THREAD

**Issue by itsjavi** [msikma/pokesprite#79]
Would be nice to add the new/updated icons introduced in the first part of the Sword/Shield DLC:

Sources: https://twitter.com/mattyoukhana_/status/1273285719960752130/photo/1
 https://twitter.com/mattyoukhana_/status/1273292610413748230/photo/1

Here is what changed:

![isle-armor-menu-sprites](https://user-images.githubusercontent.com/122741/85492432-7099a380-b5d5-11ea-8385-8519983d2f97.png)

![image](https://user-images.githubusercontent.com/122741/85908429-4e8e6400-b815-11ea-9037-4f5a1f0f1132.png)

You can find the source in the link (in case Github upload lost quality)

New forms and Pokemon:

- 025 - Pikachu - World Cap
- 080 - Slowbro - Galar
- 891 - Kubfu
- 892 - Urshifu - Single Strike Style
- 892 - Urshifu - Rapid Strike Style
- 893 - Zarude
- 893 - Zarude - Dada

There are also a few new items introduced:

- Max Honey https://github.com/kwsch/PKHeX/blob/master/PKHeX.Drawing/Resources/img/Big%20Items/bitem_1579.png
- Max Mushrooms https://github.com/kwsch/PKHeX/blob/master/PKHeX.Drawing/Resources/img/Big%20Items/bitem_1580.png
- Galarica Twig https://github.com/kwsch/PKHeX/blob/master/PKHeX.Drawing/Resources/img/Big%20Items/bitem_1581.png
- Galarica Cuff https://github.com/kwsch/PKHeX/blob/master/PKHeX.Drawing/Resources/img/Big%20Items/bitem_1582.png
- Armorite Ore https://github.com/kwsch/PKHeX/blob/master/PKHeX.Drawing/Resources/img/Big%20Items/bitem_1588.png
- Style Card https://www.serebii.net/itemdex/stylecard.shtml
- Armor Pass https://www.serebii.net/itemdex/armorpass.shtml
- Rotom Bike (Black) https://www.serebii.net/itemdex/rotombikeblack.shtml
- Rotom Bike (White) https://www.serebii.net/itemdex/rotombikewhite.shtml
- Exp. Charm https://www.serebii.net/itemdex/exp.charm.shtml
- Mark Charm https://www.serebii.net/itemdex/markcharm.shtml

**Comment by msikma** [comment]
Thanks for the overview. We're already tracking here: #76 - can you repost this there?

I've gotten started on the changes, I hope to finish in the coming week.

**Comment by itsjavi** [comment]
Hey sure I will post this issue there and close it. thanks!
