### ISSUE TITLE
Missing sprite for mimikyu-busted

### ISSUE THREAD

**Issue by nalexander50** [msikma/pokesprite#81]
On the [overview page](https://msikma.github.io/pokesprite/overview/dex-gen8.html), `mimikyu-busted` is listed, but the actual sprite shown is `mimikyu-disguised`.

**Comment by koenigderluegner** [comment]
> On the [overview page](https://msikma.github.io/pokesprite/overview/dex-gen8.html), `mimikyu-busted` is listed, but the actual sprite shown is `mimikyu-disguised`.

That's because there is no mimikyu-busted sprite, it's just a fallback. You can read more about it [here](https://github.com/msikma/pokesprite/issues/38#issuecomment-368313721)
