### ISSUE TITLE
Missing Gender forms for many Pokemon

### ISSUE THREAD

**Issue by nalexander50** [msikma/pokesprite#82]
A vast number of Pokemon have gender differences, but only a small number of them are represented in the repository.

While not great source on its own, [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/List_of_Pokémon_with_gender_differences) does have a list of gender difference Pokemon with their corresponding Pokemon HOME sprites.

I would love to see this repository updated to support all gender differences.

**Comment by msikma** [comment]
Unfortunately there aren't any more sprites for gender differences besides the ones that are in the repo right now. As in, Game Freak themselves haven't made the sprites. It looks like they don't really want to bother with it.

Of course, the HOME sprites do show gender differences, but this repo does not include the HOME images, only the pixel art sprites.

**Comment by msikma** [comment]
Closing now, but if I'm wrong and there are missing sprites let me know and I'll reopen.
