### ISSUE TITLE
Not all Pokémon have correct romanized names

### ISSUE THREAD

**Issue by msikma** [msikma/pokesprite#85]
For some reason, some romanized names are simply Hepburn transliterations of their original Japanese name. For example, Yungoos's romaji should be "Youngoose", but it's set to "Yangūsu".

Gonna write a script that checks all of them.

**Comment by lacolaco** [comment]
From a Japanese dev, thank you for the nice work. I wonder how you generate `jpn_ro`.
As feedback, actually "Youngoose" is not a Japanese-friendly Romaji form for Yungoos. Its Japanese name `ヤングース` should be transformed into Romaji "Yangūsu" but `ū` is not easy for typing, so I guess "Yangu-su" (convert to hyphen) or "Yangusu" (ignore the mark).

**Comment by msikma** [comment]
@lacolaco Game Freak has official romanizations for Pokémon that differ from regular Hepburn style romanization. "Youngoose" is one of the examples. Same with "Kameil" instead of Kamēru, and so on. That's also why there's so many "sya" (like Wakasyamo) instead of "sha". Or "Arbo" instead of Ābo. It's documented in the readme.

I decided to use Game Freak's official romanization instead of converting kana to romaji myself, but of course we could change this.

**Comment by lacolaco** [comment]
I understand. Thank you for clarification!

**Comment by msikma** [comment]
I'd be glad to change it to make it easier to use 🙂

Personally I wasn't familiar with the "official" romanized names myself and was confused by them at first. The icons might be easier to use by using "yanguusu", using "uu" instead of "ū"? Let me know what your thoughts are on this.

I'm working on a [CSS/spritesheet version](https://github.com/msikma/pokesprite-spritesheet/) and making it possible to use Japanese class names is on my todo list.

**Comment by lacolaco** [comment]
@msikma That example seems reasonable for me. marked character like "ū" is not easy to type. For example I've implemented an app which has type-ahead search box for pokemons. MosT users search Cinderace with "e-" but no results. So I've added a preprocess for "de-marking" jpn_ro. It converts "ē" into "e-". 

So, I like the idea, jpn slug for traditional Romaji.

**Comment by msikma** [comment]
I see, I'm sorry about the recent changes to the romanized names, I didn't think anyone besides me was using it. 😭 

I'll make sure there's a fix with proper romanization. Will get it fixed today. Also I would love to see your app if it's visible somewhere.

**Comment by msikma** [comment]
I've made the changes in #89. Please let me know if these changes solve the problem for you. Also I opened a new issue on #88.
