### ISSUE TITLE
Add new Alola Pokémon and forms

### ISSUE THREAD

**Issue by msikma** [msikma/pokesprite#9]
It's that time again. There are 81 new Pokémon, and several new forms.

I'm not sure if there is good reference material yet. In previous versions I used animated GIFs of shiny Pokémon (made from screen recordings) which were extremely useful because the color fidelity of those images is very good. Photos of 3DS screens are not very usable for this purpose.

**Comment by clad87** [comment]
Hi, here are all animated sprites Pokémon 7G / Alola from Sun/Moon, even regular/shiny, exept for : Minior Shiny, and Zygarde 10%/50%/100% regular/shiny

http://pokebook.net/imgs/animated_sprite_7g.zip

**Comment by msikma** [comment]
Thank you! Much appreciated!

**Comment by msikma** [comment]
Well, I've started, but it's going to take a while given how busy I am lately. I'll probably finish it in a week or so.

**Comment by msikma** [comment]
Minor update, I'm up to #790 Cosmoem. Haven't done any of the new Alola forms yet.

**Comment by clad87** [comment]
Good luck :3

**Comment by 99BenGardner** [comment]
*Minior update

**Comment by msikma** [comment]
Progress update image for those interested.

![pokesprite](https://cloud.githubusercontent.com/assets/1507745/20949535/218c2c8a-bc1a-11e6-89d8-fba6d4cb61c7.png)

**Comment by msikma** [comment]
As far as I can tell, I need to do 13 more Alola Pokémon, and 25 more Alola forms of existing Pokémon. Then I'm going to run a script to see if any icons have changed since ORAS.

Of course I won't have the item icons and other things, but I don't know if there's a dump for this available. Probably is, but I won't delay releasing the Pokémon icons for it. So I'll probably fix that later.

**Comment by msikma** [comment]
I've been using the [PKHeX](https://github.com/kwsch/PKHeX) icons to work with, but I've found at least two errors in there while going through their archive. One of them is that a Pikachu form icon is missing (Hoenn). I also think some icons are updated, but they only added new ones to PKHeX (some minor details are different in the new Pikachu forms, so I assume the other ones are also changed).

So for that reason, I'll need a complete dump of all SuMo icons before I can really finish this. Going to look for it now, but I'm not sure where to find it, other than hanging out on Project Pokémon and asking for it.

**Comment by msikma** [comment]
Except for the missing ones I mentioned before, I'm pretty much done. Going to try and get the missing icons so I can release. As usual, please let me know if you see any errors or ways to improve them.

![pokesprite](https://cloud.githubusercontent.com/assets/1507745/21029665/2220941a-bd9b-11e6-8004-557e96dff8c9.png)

**Comment by clad87** [comment]
Nice work ! :3

**Comment by msikma** [comment]
I got full dumps of everything from SuMo now, so I can finish this project.

**Comment by msikma** [comment]
Some icons have undergone very minuscule changes. Here, let's play "spot the difference" (ORAS icons left, SuMo icons right):

<img width="438" alt="screen shot 2016-12-09 at 23 10 09" src="https://cloud.githubusercontent.com/assets/1507745/21066527/468496fa-be66-11e6-8d71-10b068f897e9.png">
<img width="515" alt="screen shot 2016-12-09 at 23 20 05" src="https://cloud.githubusercontent.com/assets/1507745/21066528/469d05a0-be66-11e6-9dc8-514d60fe41af.png">

Thanks to a script I wrote that compares images, I'm able to detect these and update the icons.

**Comment by msikma** [comment]
This is now done. Haven't made a new spritesheet image yet though, but I will do that tomorrow.
