### ISSUE TITLE
Shiny Galarian Articuno Sprite Inconsistency

### ISSUE THREAD

**Issue by sora10pls** [msikma/pokesprite#95]
After further inspection, it looks as though the current Shiny sprite for Galarian Articuno is off.
The official design changes black => white and purple => blue. In addition to that, the sprite looks to have green eyes rather than light blue.
![image](https://user-images.githubusercontent.com/17801814/99911869-24a67400-2cc5-11eb-804d-65f2a7418553.png)
![image](https://user-images.githubusercontent.com/17801814/99911789-b19cfd80-2cc4-11eb-9173-8179ea75d395.png)
![b_144-1s](https://user-images.githubusercontent.com/17801814/99911797-ba8dcf00-2cc4-11eb-9743-b03e4a293599.png)

**Comment by msikma** [comment]
You're right, I'll make some adjustments. Thanks for checking.

**Comment by msikma** [comment]
How's this?

![articuno-galar](https://user-images.githubusercontent.com/1507745/99979299-3ceebf80-2da7-11eb-8197-5e3fbb4097be.png)

**Comment by sora10pls** [comment]
Looks good to me :)
