### ISSUE TITLE
Certain Sprites Not Pulling

### ISSUE THREAD

**Issue by JMLEldridge** [msikma/pokesprite#98]
Within the past week a few of the sprites stopped pulling - I tried switching from the gen8 sprites to gen7 to fill in, but neither will work.

dragonair
dragonite
mewtwo
mewtwo-mega-x
mewtwo-mega-y
mew
chikorita
bayleef
meganium
cyndaquil
quilava
typhlosion
totodile
croconaw
feraligatr
sentret
furret
hoothoot
noctowl
ledyba
ledian
spinarak
ariados
crobat
chinchou
lanturn
pichu
pichu-spiky-eared
Cleffa
igglybuff

Using the formula 
=IMAGE(CONCATENATE("https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/regular/",C216,".png"),3)
<img width="495" alt="Sprites" src="https://user-images.githubusercontent.com/76219867/102634950-36d6cf00-4118-11eb-95da-d2c56e00876a.PNG">

**Comment by msikma** [comment]
Sorry for being a bit late in responding to this. Is this still a problem? Is your spreadsheet something I can see directly?

Not sure what could cause this, as the files [appear to be there](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/regular/dragonair.png).

**Comment by JMLEldridge** [comment]
Yeah, it’s still an issue. It’s happening with cleffa (bred tab) and dragonite (event tab). 

https://docs.google.com/spreadsheets/d/1AbojEJLSzLDgDUlbY3DnCYQ29KnjxwFqa_DAD7iSgFA/edit

No worries on the delayed response, just happy you responded at all :).

**Comment by koenigderluegner** [comment]
> Yeah, it’s still an issue. It’s happening with cleffa (bred tab) and dragonite (event tab). https://docs.google.com/spreadsheets/d/1AbojEJLSzLDgDUlbY3DnCYQ29KnjxwFqa_DAD7iSgFA/edit No worries on the delayed response, just happy you responded at all :).

To fix your problem with Cleffa: in C244 your Cleffa is written with a capital C causing the not found error. you can either fix the name, change the formula to ..., lower(c244), .... or replace the formula for bulbasaur with something like this 
`=arrayformula(IMAGE(("https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/regular/"&LOWER(C2:C)&".png"),3))` (for this to work you have to clear all values **below** this formula so it can be populated by this one).

for Dragonite: I just pulled the formula cell above Dragonite into Dragonites cell and it worked (copying with changing the row numbers accordingly)

sometimes Googles caching/proxy mechainics stop loading new sprites, a simple refresh should do

**Comment by JMLEldridge** [comment]
I went ahead and switched the formula and it only populated the same
pokemon in the resource tab (still the gap from dragonair through
igglybuff) - maybe this is something wrong with my sheets that I will play
around with some. Like you said, the sprites are there so there's something
wrong with how google is pulling.

Thanks again,
Jordan M. Eldridge
*Illinois Wesleyan University* *class of* 2018
Biology/Pre-Med Major
Phone: (217)617-6640

**Comment by JMLEldridge** [comment]
After copying/pasting my entire tab to a new spreadsheet, everything started to pull. Must be something wrong with my original - thank you all so much!

**Comment by msikma** [comment]
I'm glad it was resolved. Thanks @koenigderluegner for checking it out! Let me know if any other problem crops up.
