### ISSUE TITLE
Shiny Gen8 Ho-Oh sprite inconsistency

### ISSUE THREAD

**Issue by Lusamine** [msikma/pokesprite#99]
The large shiny Ho-Oh sprite's beak is the wrong color.

https://github.com/msikma/pokesprite/blob/master/pokemon-gen8/shiny/ho-oh.png

It should be silver like the head feathers and tail.
Comparison: https://www.serebii.net/pokedex-swsh/ho-oh/

**Comment by msikma** [comment]
Thanks for letting me know! I'll fix it when I've got some time.

**Comment by msikma** [comment]
Does this look better? I also think its body was maybe a bit too yellow compared to the reference so I made it a bit more orange.

![ho-oh](https://user-images.githubusercontent.com/1507745/111036801-6cdad500-8421-11eb-9e61-19db784eee82.png)
